### ISSUE TITLE
Json format changes in spring data rest

### ISSUE THREAD

**Issue by zerouwar** [FasterXML/jackson-datatype-hibernate#108]
I am using spring data rest and add `jackson-datatype-hibernate5` (version is 2.9.0) to solve the lazy serialization problem.The problem was solved but json format was be changed.

**This was only appeared at getting sub-resource.**

Example,I want to get the `userBroker` of house and GET http://localhost:8070/houses/house2/userBroker

no `jackson-datatype-hibernate5`,json will be

```
{
    "username": "test",
    "password": "123",
    "name": "测试经济人",
    "phone": "122",
    "integral": 0,
    "startLevel": 1,
    "isGold": "否",
     "handler":{},
     "hibernateLazyInitializer":{},
    "_links": {
        ...
     }
}
```

PS:I set`SerializationFeature.FAIL_ON_EMPTY_BEANS` as false.

and added `jackson-datatype-hibernate5`

```
{
    "content": {
        "username": "test",
        "password": "123",
        "name": "测试经济人",
        "phone": "122",
        "integral": 0,
        "startLevel": 1,
        "isGold": "否"
    },
    "_links": {
    ...
    }
}
```

**Comment by cowtowncoder** [comment]
Unfortunately I can not reproduce your issue without code showing what you are doing.

**Comment by zerouwar** [comment]
My oversight,I make a simple demo on [github](https://github.com/zerouwar/Hibernate5ModuleIssueDemo/tree/master).It can reproduce the issue.

**Comment by cowtowncoder** [comment]
Not sure if this is active problem or not, but reproduction would have to be without using any of Spring components, only using Jackson components.

**Comment by wilker7ribeiro** [comment]
I'm having the same issue

**Comment by cowtowncoder** [comment]
Closing, would need a _stand-alone_ test(s) that do not rely on other frameworks. May be re-opened with that.
