### ISSUE TITLE
how to avoid jackson to generate this loop

### ISSUE THREAD

**Issue by gianpaolodn** [FasterXML/jackson-datatype-hibernate#112]
Hi, We are getting mad with this, and any help is appreciated.

Setup: Two tables with a join table with attributes
Stack: spring boot 1.5.7 + hibernate 5.2.11 + jackson 

```
class A {

    public String id;
   
    @OneToMany
    public Set<AB> AB;

}

class AB {

  String some_other_field;

  @ManyToOne A

  @ManyToOne B

}

class B {

    public String id;
   
    @OneToMany
    public Set<AB> AB;

}
```

This generates a loop when jackson produce the json, and we solved this putting the @Jsonignore properties in the class AB for the manytoone relations. But in this way we can't produce the json we want with these possible scenarios.

calling for example a rest endpoint 
www.restendpoint.com/v1/A/1/

We would like to have all the info of A without AB (and this should be done using the LAZY fetch)

calling instead: 
www.restendpoint.com/v1/B/1/

We would like to have all the info of B without AB (as above with LAZY)

instead calling this:
www.restendpoint.com/v1/A/1/listofB

should return:

```
result {
   A.id;
   A.AB {
      //relation with A should be ignored
      AB.some_other_field;
      AB.B {
         B.id;
         //relation with AB should be ignored
      }
   }
}
```

and when calling 
www.restendpoint.com/v1/B/1/listofA 

```
result {
   B.id;
   B.AB {
      //relation with B should be ignored
      AB.some_other_field;
      AB.A {
         A.id;
         //relation with AB should be ignored
      }
   }
}
```

Thanks!

**Comment by cowtowncoder** [comment]
First of all, issue tracker is not a help forum: you'd be better off using

https://groups.google.com/forum/#!forum/jackson-user

for usage questions.

But before doing that, you probably want to read this:

http://www.baeldung.com/jackson-bidirectional-relationships-and-infinite-recursion
