### ISSUE TITLE
Want to work on JDK 1.6?

### ISSUE THREAD

**Issue by pool13433** [FasterXML/jackson-datatype-hibernate#114]
My web server uses your JDK 1.6 Library as a 1.7 up support. I would like to use 1.6 ; How to ?

**Comment by cowtowncoder** [comment]
Please use mailing lists for usage questions: this is issue tracker, used for reporting issues.

As to JDK 1.6: you should be able to use all Jackson 2.x versions still. If you have problems you may want to try older versions; 2.6 was the last version that can be built on JDK 1.6.
