### ISSUE TITLE
`HibernateAnnotationIntrospector` strongly depends on `javax.persistence.Transient`

### ISSUE THREAD

**Issue by odrotbohm** [FasterXML/jackson-datatype-hibernate#145]
We're in the process of preparing Spring (Data) to move to JakartaEE and Spring Data REST stumbles over the fact that `HibernateAnnotationIntrospector` tries to load `javax.persistence.Transient` in `….hasIgnoreMarker(…)`.

Would you mind to reflectively obtain that particular class or the JakartaEE equivalent so that the module can be used in JakartaEE environments, too?

**Comment by cowtowncoder** [comment]
@odrotbohm no problem; I hope this works for you.
