### ISSUE TITLE
Module for Hibernate 6

### ISSUE THREAD

**Issue by zUniQueX** [FasterXML/jackson-datatype-hibernate#158]
Are there any plans for development of a module for Hibernate 6 or rather 6.1 yet?

**Comment by cowtowncoder** [comment]
Yes, if someone contributes an implementation. Unfortunately this module is without active owner at this point and is thereby not well supported.

**Comment by MartinHlavna** [comment]
Looks like Hibernate 5 Jakarta module works for Hibernate 6 at the moment.  I did test only basic serialization of "lazy proxies" though.

**Comment by cowtowncoder** [comment]
Thank you @MartinHlavna -- maybe this encourages others to try it out, see how well it works.

**Comment by zUniQueX** [comment]
> Thank you @MartinHlavna -- maybe this encourages others to try it out, see how well it works.
> 

@cowtowncoder I've read the migration guide for Hibernate 6 and 6.1 and didn't see an issue for the Jakarta Jackson module, so this is my current workaround too.

**Comment by cowtowncoder** [comment]
@MartinHlavna @zUniQueX thank you! One thing that'd be helpful if anyone has time would be a little PR for change(s) to README, mentioning compatibility.
