### ISSUE TITLE
jackson-datatype-hibernate6 not found with maven

### ISSUE THREAD

**Issue by 1hamidreza** [FasterXML/jackson-datatype-hibernate#169]
I've added below as advised in the README to my pom.xml : 

```
<dependency>
    <groupId>com.fasterxml.jackson.datatype</groupId>
    <artifactId>jackson-datatype-hibernate6</artifactId>
    <version>2.15.0</version>
</dependency>
```

Maven saying that the dependency not found. When changing it to hibernate5 with version 2.14.1 it founds. 
Can someone advise about the issue ?

_Hamid

**Comment by pjfanning** [comment]
v2.15.0 is yet released - will be ready in a month (or 2).
