### ISSUE TITLE
When is version 2.15.0 scheduled to release?

### ISSUE THREAD

**Issue by ikannak** [FasterXML/jackson-datatype-hibernate#170]
We are upgrading a project from Spring Boot 2.7.0 to Spring Boot 3.0.4, which includes an upgrade to Hibernate 6.1. We have a dependency on jackson-datatype-hibernate as such:

> implementation 'com.fasterxml.jackson.datatype:jackson-datatype-hibernate5:2.13.3'

This version broke because of the javax -> Jakarta migration. We have updated the dependencies to use:

> implementation 'com.fasterxml.jackson.datatype:jackson-datatype-hibernate5-jakarta'

This appears to work (our tests succeeded at least), but we would still prefer to use a version which is explicitly compatible with Hibernate 6.X. According to the documentation, this is version 2.15.0. So my question is: when are you planning on releasing version 2.15.0?

**Comment by pjfanning** [comment]
Issues are for tracking bugs

**Comment by ikannak** [comment]
Okay, then where SHOULD I ask this question then? Do you have a mailing list or non-Github page where I can ask this question?

**Comment by pjfanning** [comment]
* https://github.com/FasterXML/jackson/blob/master/CONTRIBUTING.md
* https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.15

**Comment by ikannak** [comment]
@cowtowncoder  I see. I'm currently using the hibernate5-jakarta release, and it appears to be compatible enough with Hibernate 6.1 that everything I've tried so far works just fine. That said, I don't know if there are any gotchas in this usecase where it appears to work but in actuality has a glaring flaw that can lead to data corruption.
