### ISSUE TITLE
CI snapshot publish is broken

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-datatype-hibernate#172]
I tried https://github.com/FasterXML/jackson-datatype-hibernate/commit/51b87f6557e56758fc20ee6b6f5e19879beed832 but there is now a 401 coming back from Sonatype.

**Comment by cowtowncoder** [comment]
Hmmhm. Odd. Ok, I'll see what re-run does if it was transient problem. Should not matter you checked it in wrt access, since it's in `master` now.

**Comment by cowtowncoder** [comment]
Ah! I know what it is -- secret needed is not enabled for this repo (by FasterXML org). I _thought_ I had fixed it but maybe it didn't save.
Will verify it'll get enabled.

**Comment by cowtowncoder** [comment]
Finally works with access to deploy/publish Secret.
