### ISSUE TITLE
remove scm tag from pom?

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-datatype-hibernate#177]
This tag complicates releases etc.

https://github.com/FasterXML/jackson-datatype-hibernate/blob/290ed9942a2f837e8ee75095d5f314408b8fb9a8/pom.xml#L32

Can we just consider omitting it and letting users worry about the tag? As part of the release, we also publish a sources jar and IDEs would typically use that if users wanted to see the source for a Jackson class.

fyi @cowtowncoder

**Comment by cowtowncoder** [comment]
@pjfanning `<tag>` should be modified by Maven release plug-in as part of release process so I don't think its committed value is actually used for anything.
Most of the time it should be left as:

    <tag>HEAD</tag>

I think. I can change it; not sure why it was left at an old value.
I am not sure it is needed by release plug-in but its existence in general has seemed harmless.

**Comment by cowtowncoder** [comment]
Fwtw the way I publish new versions is with

    ./mvnw release:clean release:prepare release:perform

assuming version is at `-SNAPSHOT` for package itself (and `jackson-base` at published non-snapshot version)
