### ISSUE TITLE
@JsonInclude doesn't work with hibernate POJOS

### ISSUE THREAD

**Issue by czegarram** [FasterXML/jackson-datatype-hibernate#48]
@JsonInclude(Include.NON_NULL)  @JsonInclude(Include.DEFAULT)  @JsonInclude(Include.NON_EMPTY)  

Tested with Hibernate 4.1.10FINAL, Spring Framework 3

**Comment by sanjutoyou** [comment]
It still doesn't work. I have tested with hibernate 4.3.7Final and Jackson 2.4.

**Comment by cowtowncoder** [comment]
@sanjutoyou I need a reproducible test case here; often times working (or not) depends on some aspect of structuring (root level value vs property, included in an array or Collection etc).
A small code snippet may work as well, although isolated test case would be optimal.

**Comment by renatoaraujoc** [comment]
I've had problems with Hibernate when @cowtowncoder fixed the @Transient tags. I sent him an email yesterday regarding this issue and now I got it fixed.

This code fixed: hibernate4Module.configure(Hibernate4Module.Feature.USE_TRANSIENT_ANNOTATION, false);

Hope I could be of help.

**Comment by sanjutoyou** [comment]
please find the reference for the issue I raised  -  https://github.com/FasterXML/jackson-annotations/issues/53

And the description - 
http://stackoverflow.com/questions/27959267/jsonincludeinclude-non-null-not-working-jackson-serializing-null-values/27974849#27974849
