### ISSUE TITLE
Feature.SERIALIZE_IDENTIFIER_FOR_LAZY_NOT_LOADED_OBJECTS customise generated name

### ISSUE THREAD

**Issue by jackmatt2** [FasterXML/jackson-datatype-hibernate#50]
It would be good if Feature.SERIALIZE_IDENTIFIER_FOR_LAZY_NOT_LOADED_OBJECTS would let you customise the generated name, or at least use the name from the java bean.

Currently it is serializing using full package and class name:

"client":{"com.test.domain.Client":1}

I want it to use the id instead (which is the name of the attribute in the hibernate entity):

"client":{"id":1}

Maybe there is a way around this but I can't find any.

**Comment by Mohamed-Mamdouh** [comment]
Hello Guys.
Am facing the same issue regarding the naming of the Ids and wonder if any implemented the recommended fix ?

**Comment by bedag-moo** [comment]
It is worth noting that the HibernateSerializer uses the actual name of the id property if the session is still open, or the hibernate mapping is passed to the Hibernate4Module constructor.

Still, it would be nice if the Serializer could infer this information automatically in all cases.

**Comment by cowtowncoder** [comment]
At this point, what I really need is a unit test that shows expected behavior; solutions are only useful once problem is shown.

**Comment by bedag-moo** [comment]
I don't have time to write a full test, but I can clarify the behaviour I would expect, and that @jackmatt2 probably means when he says "use the property from the java bean":

Given an entity

    @Entity
    public class MyEntity {
        @Id
        private String id;

        public String getId() {
            return id;
        }

        public String setId(String id) {
            this.id = id;
        }
    }

or an entity

    @Entity
    public class MyEntity {
        private String id;

        @Id
        public String getId() {
            return id;
        }

        public String setId(String id) {
            this.id = id;
        }
    }

or an entity

    @Entity
    public class MyEntity extends BaseEntity {
    }

where

    @MappedSuperclass
    public abstract class BaseEntity {
        @Id
        private String id;

        public String getId() {
            return id;
        }

        public String setId(String id) {
            this.id = id;
        }
    }   

the following should pass:

    EntityManager entityManager = entityManagerFactory.createEntityManager();
    try {
        // an uninitialised lazy loading proxy
        proxy = entityManager.getReference(MyEntity.class, "42"); 
    } finally {
        // is detached
        entityManager.close();                                                
    }

    // but can still be marshalled correctly
    assertEquals("{"id":"42"}", objectMapper.writeValueAsString(proxy));

**Comment by cowtowncoder** [comment]
@bedag-moo Perhaps someone can find time to work on this, either on writing the test, or working using other means to resolve it. I do not use Hibernate and my time is spread across many jackson modules, so this will not be high priority.

**Comment by cm325** [comment]
It would appear that this actually does work, as long as you instantiate the Hibernate4Module with the hibernate mappings:

http://stackoverflow.com/questions/21472926/override-id-name-generated-by-jackson-datatype-hibernate

What I can't figure out is how to get a handle on the LocalSessionFactoryBean in a spring boot app in order to provide the mappings. Any ideas?

**Comment by cm325** [comment]
Oh, nevermind, I realized I can cast the sessionFactory to "Mappings" and it works. I used this technique to get the sessionFactory in spring boot - http://stackoverflow.com/a/33881946/228369
