### ISSUE TITLE
@Transient annotations are not being serialized

### ISSUE THREAD

**Issue by papaulaza** [FasterXML/jackson-datatype-hibernate#61]
I'm configuring HibernateObjectAwareMapper in the following way, but @Transient fields are not being serialized after updating to version 2.3.3.

```java
public HibernateAwareObjectMapper() {
        Hibernate4Module hm = new Hibernate4Module();
        hm.disable(Hibernate4Module.Feature.USE_TRANSIENT_ANNOTATION);
        registerModule(hm);
    }
```

**Comment by renatoaraujoc** [comment]
Try this
hibernate4Module.configure(Hibernate4Module.Feature.USE_TRANSIENT_ANNOTATION, false);

**Comment by cowtowncoder** [comment]
Can not reproduce without unit test; may be reopened with a failing unit test.
