### ISSUE TITLE
Provide support for hibernate 5 

### ISSUE THREAD

**Issue by paranoiabla** [FasterXML/jackson-datatype-hibernate#67]
Just as a follow-up on this one:

https://jira.spring.io/browse/DATAREST-545

I don't think the project works with hibernate5. Hibernate5 beta2 is out already - please verify the project works and implement if it doesn't :)

**Comment by cowtowncoder** [comment]
Implemented via #68

**Comment by cowtowncoder** [comment]
One comment: due to major version upgrade, there is now new `hibernate5` sub-module (similar to `hibernate3` and `hibernate4`), as well matching `Hibernate5Module.java`.
