### ISSUE TITLE
Infinite recursion due to `@JsonIgnoreProperties` not applicable to `List` valued property

### ISSUE THREAD

**Issue by peruzzo** [FasterXML/jackson-datatype-hibernate#70]
I have a stackoverflow problem, but it occurs only depending on the entity that initialize first.

```javascript
@Entity @Table(name="contrato")
public class Contrato {

	@Id
	private Long id;
	
	private String numeroContrato;
	
	@OneToMany(mappedBy="contrato") @JsonIgnoreProperties("contrato")
	private List<Parcela> parcelas;
	
	@OneToMany(mappedBy="contrato") @JsonIgnoreProperties("contrato")
	private List<Liquidacao> liquidacoes;
}

@Entity @Table(name="contrato_parcela")
public class Parcela {
	
	@Id
	private Long id;
	
	private Integer numeroParcela;	
	
	@ManyToOne(fetch=FetchType.LAZY) @JoinColumn(name="contrato_id")
	private Contrato contrato;
}

@Entity @Table(name="contrato_liquidacao")
public class Liquidacao {
	
	@Id
	private Long id;

	private BigDecimal valorTotal;
	
	@ManyToOne(fetch=FetchType.LAZY) @JoinColumn(name="contrato_id")
	private Contrato contrato;
	
	@ManyToOne(fetch=FetchType.LAZY) @JoinColumn(name="contrato_parcela_id") @JsonIgnoreProperties("contrato")
	private Parcela parcela;
}
```

This block below works perfectly with the expected return:  {"numeroContrato":"101-6861944","parcelas":[{"numeroParcela":3}],"liquidacoes":[{"valorTotal":91548.00,"parcela":{"numeroParcela":3}}]}

```javascript
final Contrato contrato = em.find(Contrato.class, 1L);
Hibernate.initialize(contrato.getParcelas());
Hibernate.initialize(contrato.getLiquidacoes());
mapper.writer().writeValueAsString(contrato);
```

But that other code block, where I changed the boot order of the relationship I have a stackoverflow.

```javascript
Contrato contrato = em.find(Contrato.class, 1L);
Hibernate.initialize(contrato.getLiquidacoes());
Hibernate.initialize(contrato.getParcelas());
mapper.writer().writeValueAsString(contrato); 
```

Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError) (through reference chain: teste.jackson.Contrato["parcelas"]->org.hibernate.collection.internal.PersistentBag[0]->teste.jackson.Parcela["contrato"]->teste.jackson.Contrato["parcelas"]->org.hibernate.collection.internal.PersistentBag[0]->teste.jackson.Parcela["contrato"]->teste.jackson.Contrato["parcelas"]->org.hibernate.collection.internal.PersistentBag[0]->teste.jackson.Parcela["contrato"]->teste.jackson.Contrato["parcelas"]->org.hibernate.collection.internal.PersistentBag[0] ...

**Comment by peruzzo** [comment]
I believe that solving the problem is to make the class HibernateProxySerializer implement the ContextualSerializer interface. This way you can have accesso to BeanProperty in serialize method.

**Comment by mperuzzo** [comment]
+1

**Comment by cowtowncoder** [comment]
What would be useful here is a self-contained unit test.

**Comment by peruzzo** [comment]
@cowtowncoder  He came to look at my suggestion to fix this issue #82 ? I try to see the other way if you do not find a valid solution.

**Comment by cowtowncoder** [comment]
@peruzzo Thanks -- I'll have a look at this now.

**Comment by peruzzo** [comment]
@cowtowncoder  Thanks! :smiley:
