### ISSUE TITLE
Should ignore org.hibernate.bytecode.internal.javassist.FieldHandled.getFieldHandler()

### ISSUE THREAD

**Issue by candrews** [FasterXML/jackson-datatype-hibernate#72]
When using bytecode enhancement, Hibernate classes get a new field, "fieldHandler" from the org.hibernate.bytecode.internal.javassist.FieldHandled interface. You can see how to set up bytecode enhancement and see what the generated code looks like at http://vladmihalcea.com/2014/09/08/hibernate-bytecode-enhancement/

This field should not be serialized/deserialized by Jackson.

Here's the module I've made to workaround this:

	private static class FiledHandledModule extends SimpleModule {
		private abstract class FieldHandledMixIn implements FieldHandled {

			@Override
			@JsonIgnore
			public abstract void setFieldHandler(FieldHandler handler);

			@Override
			@JsonIgnore
			public abstract  FieldHandler getFieldHandler();
			
		}

		@Override
		public void setupModule(SetupContext context) {
			super.setupModule(context);
			context.setMixInAnnotations(FieldHandled.class, FieldHandledMixIn.class);
		}
		
	}

**Comment by cowtowncoder** [comment]
Thank you for reporting this.

From the article, it sounds like version 4.2.8 of Hibernate and above may be affected.
Do you think it'd be easy to come with a unit test that shows the problem?

I'll have to think about the best way to approach this: mix-in is one possibility, but perhaps "ignore type" could also work, to drop the property with `FieldHandler` value.

**Comment by candrews** [comment]
Based on git history, https://github.com/hibernate/hibernate-orm/blob/master/hibernate-core/src/main/java/org/hibernate/bytecode/internal/javassist/FieldHandled.java has existed since Hibernate 4.0 and continues to exist in Hibernate 5. So I think it's safe to ignore its fields for all Hibernate 4 and 5 versions.

**Comment by cowtowncoder** [comment]
Ok makes sense; thank you for verifying.

**Comment by cowtowncoder** [comment]
This would be easyish to implement if [https://github.com/FasterXML/jackson-databind/issues/861] was implemented. Until then, should be relatively easy to implement by making `HibernateAnnotationIntrospector` override `AnnotationIntrospector.isIgnorableType()`.

In fact, the bigger piece that is needed is really the unit test to verify the fix.
I would be happy to merge a PR for this! :)

**Comment by cowtowncoder** [comment]
Ok. I added possible fix for annotation introspectors, but unfortunately I have no way to test whether that actually works. If fix does not work a unit test would be welcome, and issue may be reopened.

**Comment by cowtowncoder** [comment]
Oy vey. As per #86, this type is now removed from Hibernate 5.1.
But sounds like it is still needed for 5.0. Also not certain if replacement functionality would be needed.
