### ISSUE TITLE
Spring Data with Rest, not working with this patch...

### ISSUE THREAD

**Issue by jackp55** [FasterXML/jackson-datatype-hibernate#83]
Hi there,

I've tried your solution to get rid of the Spring Data Rest issue https://jira.spring.io/browse/DATAJPA-630 , but i'm still getting a 'No serializer found for class org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer' error, any ideas?

thx!
JackP

**Comment by cowtowncoder** [comment]
Please use mailing lists for question, instead of issue tracker. Tracker is for reporting bugs.
