### ISSUE TITLE
Source files without license headers

### ISSUE THREAD

**Issue by puntogil** [FasterXML/jackson-datatype-hibernate#89]
Hi
All java source files are without license headers. Please, confirm the licensing of code and/or content/s, and add license headers
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification
Thanks in advance

**Comment by cowtowncoder** [comment]
@puntogil Source files are not to contain license declarations; these are pure overhead serving no purpose whatsoever. Licensing is indicated in `pom.xml` as well as jars being built.

**Comment by puntogil** [comment]
Is not enough for our packaging guideline (Fedora)
